#!/bin/bash
#SBATCH --job-name=LR_test_3e-4_3e-1_dpr
#SBATCH -M ukko
#SBATCH -p gpu
#SBATCH -o LR_test_3e-4_3e-1_dpr.txt
#SBATCH -c 2
#SBATCH -t 23:59:00
#SBATCH --mem-per-cpu=16G
#SBATCH --gres=gpu:1

module purge
module load CUDA
module load cuDNN
conda activate tpnica

srun --unbuffered python main.py --headless -D1 --L-est 1 --L-data 0 --theta-learning-rate 3e-4 --phi-learning-rate 3e-1 --num-s-samples 1 --num-tau-samples 1 --burn-in-len 0
