#!/bin/bash
#SBATCH --job-name=tp_l0_d2_large_v2
#SBATCH -M ukko
#SBATCH -p gpu,gpu-long
#SBATCH -o tp_l0_d2_large_v2.txt
#SBATCH -c 2
#SBATCH -t 23:59:00
#SBATCH --mem-per-cpu=64G
#SBATCH --gres=gpu:1
#SBATCH --array=3-4

module purge
mamba activate tpnica

srun --unbuffered python main.py --headless -D2 -N12 -M24 --num-pseudo 100 --data-seed $SLURM_ARRAY_TASK_ID --L-data 0 --L-est 0 --repeat-kernels
