#!/bin/bash
#SBATCH --job-name=unique_dfs
#SBATCH -M kale 
#SBATCH -p gpu,gpu-short
#SBATCH -o unique_dfs.txt
#SBATCH -c 2
#SBATCH -t 23:59:00
#SBATCH --mem-per-cpu=64G
#SBATCH --gres=gpu:1
#SBATCH --array=1-4

module purge
module load CUDA
module load cuDNN
conda activate tpnica

srun --unbuffered python main.py --headless -D1 --num-data 1024 --repeat-kernels --data-seed $SLURM_ARRAY_TASK_ID --resume-ckpt
